apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: techtrends
    repoURL:
    https://github.com/kgamanji/argocd-demo
  syncPolicy: {}